// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package ma.projet.grpc.stubs;

public interface GetReservationsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetReservationsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Liste des réservations
   * </pre>
   *
   * <code>repeated .Reservation reservations = 1;</code>
   */
  java.util.List<ma.projet.grpc.stubs.Reservation> 
      getReservationsList();
  /**
   * <pre>
   * Liste des réservations
   * </pre>
   *
   * <code>repeated .Reservation reservations = 1;</code>
   */
  ma.projet.grpc.stubs.Reservation getReservations(int index);
  /**
   * <pre>
   * Liste des réservations
   * </pre>
   *
   * <code>repeated .Reservation reservations = 1;</code>
   */
  int getReservationsCount();
  /**
   * <pre>
   * Liste des réservations
   * </pre>
   *
   * <code>repeated .Reservation reservations = 1;</code>
   */
  java.util.List<? extends ma.projet.grpc.stubs.ReservationOrBuilder> 
      getReservationsOrBuilderList();
  /**
   * <pre>
   * Liste des réservations
   * </pre>
   *
   * <code>repeated .Reservation reservations = 1;</code>
   */
  ma.projet.grpc.stubs.ReservationOrBuilder getReservationsOrBuilder(
      int index);
}
