// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package ma.projet.grpc.stubs;

public interface GetReservationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetReservationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Détails de la réservation
   * </pre>
   *
   * <code>.Reservation reservation = 1;</code>
   * @return Whether the reservation field is set.
   */
  boolean hasReservation();
  /**
   * <pre>
   * Détails de la réservation
   * </pre>
   *
   * <code>.Reservation reservation = 1;</code>
   * @return The reservation.
   */
  ma.projet.grpc.stubs.Reservation getReservation();
  /**
   * <pre>
   * Détails de la réservation
   * </pre>
   *
   * <code>.Reservation reservation = 1;</code>
   */
  ma.projet.grpc.stubs.ReservationOrBuilder getReservationOrBuilder();
}
