// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package ma.projet.grpc.stubs;

public interface GetReservationsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetReservationsRequest)
    com.google.protobuf.MessageOrBuilder {
}
