// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package ma.projet.grpc.stubs;

public interface GetReservationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetReservationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID de la réservation
   * </pre>
   *
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();
}
