// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package ma.projet.grpc.stubs;

public final class ReservationOuterClass {
  private ReservationOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Client_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Client_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Chambre_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Chambre_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Reservation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Reservation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateReservationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateReservationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021reservation.proto\032\037google/protobuf/tim" +
      "estamp.proto\032\033google/protobuf/empty.prot" +
      "o\"S\n\006Client\022\n\n\002id\030\001 \001(\003\022\013\n\003nom\030\002 \001(\t\022\016\n\006" +
      "prenom\030\003 \001(\t\022\r\n\005email\030\004 \001(\t\022\021\n\ttelephone" +
      "\030\005 \001(\t\"E\n\007Chambre\022\n\n\002id\030\001 \001(\003\022\014\n\004type\030\002 " +
      "\001(\t\022\014\n\004prix\030\003 \001(\002\022\022\n\ndisponible\030\004 \001(\010\"\276\001" +
      "\n\013Reservation\022\n\n\002id\030\001 \001(\003\022\027\n\006client\030\002 \001(" +
      "\0132\007.Client\022\031\n\007chambre\030\003 \001(\0132\010.Chambre\022-\n" +
      "\tdateDebut\030\004 \001(\0132\032.google.protobuf.Times" +
      "tamp\022+\n\007dateFin\030\005 \001(\0132\032.google.protobuf." +
      "Timestamp\022\023\n\013preferences\030\006 \001(\t\"\030\n\026GetRes" +
      "ervationsRequest\"=\n\027GetReservationsRespo" +
      "nse\022\"\n\014reservations\030\001 \003(\0132\014.Reservation\"" +
      "#\n\025GetReservationRequest\022\n\n\002id\030\001 \001(\003\";\n\026" +
      "GetReservationResponse\022!\n\013reservation\030\001 " +
      "\001(\0132\014.Reservation\"x\n\030CreateReservationRe" +
      "quest\022\020\n\010clientId\030\001 \001(\003\022\021\n\tchambreId\030\002 \001" +
      "(\003\022\021\n\tdateDebut\030\003 \001(\t\022\017\n\007dateFin\030\004 \001(\t\022\023" +
      "\n\013preferences\030\005 \001(\t\">\n\031CreateReservation" +
      "Response\022!\n\013reservation\030\001 \001(\0132\014.Reservat" +
      "ion2\256\002\n\022ReservationService\022D\n\017GetReserva" +
      "tions\022\027.GetReservationsRequest\032\030.GetRese" +
      "rvationsResponse\022A\n\016GetReservation\022\026.Get" +
      "ReservationRequest\032\027.GetReservationRespo" +
      "nse\022J\n\021CreateReservation\022\031.CreateReserva" +
      "tionRequest\032\032.CreateReservationResponse\022" +
      "C\n\021DeleteReservation\022\026.GetReservationReq" +
      "uest\032\026.google.protobuf.EmptyB\030\n\024ma.proje" +
      "t.grpc.stubsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_Client_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Client_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Client_descriptor,
        new java.lang.String[] { "Id", "Nom", "Prenom", "Email", "Telephone", });
    internal_static_Chambre_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Chambre_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Chambre_descriptor,
        new java.lang.String[] { "Id", "Type", "Prix", "Disponible", });
    internal_static_Reservation_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Reservation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Reservation_descriptor,
        new java.lang.String[] { "Id", "Client", "Chambre", "DateDebut", "DateFin", "Preferences", });
    internal_static_GetReservationsRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetReservationsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetReservationsResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_GetReservationsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationsResponse_descriptor,
        new java.lang.String[] { "Reservations", });
    internal_static_GetReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GetReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GetReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_GetReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationResponse_descriptor,
        new java.lang.String[] { "Reservation", });
    internal_static_CreateReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_CreateReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateReservationRequest_descriptor,
        new java.lang.String[] { "ClientId", "ChambreId", "DateDebut", "DateFin", "Preferences", });
    internal_static_CreateReservationResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_CreateReservationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateReservationResponse_descriptor,
        new java.lang.String[] { "Reservation", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
