// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package ma.projet.grpc.stubs;

/**
 * <pre>
 * Message pour la réservation
 * </pre>
 *
 * Protobuf type {@code Reservation}
 */
public  final class Reservation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Reservation)
    ReservationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Reservation.newBuilder() to construct.
  private Reservation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Reservation() {
    preferences_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Reservation();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Reservation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            ma.projet.grpc.stubs.Client.Builder subBuilder = null;
            if (client_ != null) {
              subBuilder = client_.toBuilder();
            }
            client_ = input.readMessage(ma.projet.grpc.stubs.Client.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(client_);
              client_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            ma.projet.grpc.stubs.Chambre.Builder subBuilder = null;
            if (chambre_ != null) {
              subBuilder = chambre_.toBuilder();
            }
            chambre_ = input.readMessage(ma.projet.grpc.stubs.Chambre.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(chambre_);
              chambre_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (dateDebut_ != null) {
              subBuilder = dateDebut_.toBuilder();
            }
            dateDebut_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dateDebut_);
              dateDebut_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (dateFin_ != null) {
              subBuilder = dateFin_.toBuilder();
            }
            dateFin_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dateFin_);
              dateFin_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            preferences_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ma.projet.grpc.stubs.ReservationOuterClass.internal_static_Reservation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ma.projet.grpc.stubs.ReservationOuterClass.internal_static_Reservation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ma.projet.grpc.stubs.Reservation.class, ma.projet.grpc.stubs.Reservation.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <pre>
   * ID de la réservation
   * </pre>
   *
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  public long getId() {
    return id_;
  }

  public static final int CLIENT_FIELD_NUMBER = 2;
  private ma.projet.grpc.stubs.Client client_;
  /**
   * <pre>
   * Le client qui effectue la réservation
   * </pre>
   *
   * <code>.Client client = 2;</code>
   * @return Whether the client field is set.
   */
  public boolean hasClient() {
    return client_ != null;
  }
  /**
   * <pre>
   * Le client qui effectue la réservation
   * </pre>
   *
   * <code>.Client client = 2;</code>
   * @return The client.
   */
  public ma.projet.grpc.stubs.Client getClient() {
    return client_ == null ? ma.projet.grpc.stubs.Client.getDefaultInstance() : client_;
  }
  /**
   * <pre>
   * Le client qui effectue la réservation
   * </pre>
   *
   * <code>.Client client = 2;</code>
   */
  public ma.projet.grpc.stubs.ClientOrBuilder getClientOrBuilder() {
    return getClient();
  }

  public static final int CHAMBRE_FIELD_NUMBER = 3;
  private ma.projet.grpc.stubs.Chambre chambre_;
  /**
   * <pre>
   * La chambre réservée
   * </pre>
   *
   * <code>.Chambre chambre = 3;</code>
   * @return Whether the chambre field is set.
   */
  public boolean hasChambre() {
    return chambre_ != null;
  }
  /**
   * <pre>
   * La chambre réservée
   * </pre>
   *
   * <code>.Chambre chambre = 3;</code>
   * @return The chambre.
   */
  public ma.projet.grpc.stubs.Chambre getChambre() {
    return chambre_ == null ? ma.projet.grpc.stubs.Chambre.getDefaultInstance() : chambre_;
  }
  /**
   * <pre>
   * La chambre réservée
   * </pre>
   *
   * <code>.Chambre chambre = 3;</code>
   */
  public ma.projet.grpc.stubs.ChambreOrBuilder getChambreOrBuilder() {
    return getChambre();
  }

  public static final int DATEDEBUT_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp dateDebut_;
  /**
   * <pre>
   * Date de début de la réservation
   * </pre>
   *
   * <code>.google.protobuf.Timestamp dateDebut = 4;</code>
   * @return Whether the dateDebut field is set.
   */
  public boolean hasDateDebut() {
    return dateDebut_ != null;
  }
  /**
   * <pre>
   * Date de début de la réservation
   * </pre>
   *
   * <code>.google.protobuf.Timestamp dateDebut = 4;</code>
   * @return The dateDebut.
   */
  public com.google.protobuf.Timestamp getDateDebut() {
    return dateDebut_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateDebut_;
  }
  /**
   * <pre>
   * Date de début de la réservation
   * </pre>
   *
   * <code>.google.protobuf.Timestamp dateDebut = 4;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getDateDebutOrBuilder() {
    return getDateDebut();
  }

  public static final int DATEFIN_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp dateFin_;
  /**
   * <pre>
   * Date de fin de la réservation
   * </pre>
   *
   * <code>.google.protobuf.Timestamp dateFin = 5;</code>
   * @return Whether the dateFin field is set.
   */
  public boolean hasDateFin() {
    return dateFin_ != null;
  }
  /**
   * <pre>
   * Date de fin de la réservation
   * </pre>
   *
   * <code>.google.protobuf.Timestamp dateFin = 5;</code>
   * @return The dateFin.
   */
  public com.google.protobuf.Timestamp getDateFin() {
    return dateFin_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateFin_;
  }
  /**
   * <pre>
   * Date de fin de la réservation
   * </pre>
   *
   * <code>.google.protobuf.Timestamp dateFin = 5;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getDateFinOrBuilder() {
    return getDateFin();
  }

  public static final int PREFERENCES_FIELD_NUMBER = 6;
  private volatile java.lang.Object preferences_;
  /**
   * <pre>
   * Préférences du client
   * </pre>
   *
   * <code>string preferences = 6;</code>
   * @return The preferences.
   */
  public java.lang.String getPreferences() {
    java.lang.Object ref = preferences_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      preferences_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Préférences du client
   * </pre>
   *
   * <code>string preferences = 6;</code>
   * @return The bytes for preferences.
   */
  public com.google.protobuf.ByteString
      getPreferencesBytes() {
    java.lang.Object ref = preferences_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      preferences_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (client_ != null) {
      output.writeMessage(2, getClient());
    }
    if (chambre_ != null) {
      output.writeMessage(3, getChambre());
    }
    if (dateDebut_ != null) {
      output.writeMessage(4, getDateDebut());
    }
    if (dateFin_ != null) {
      output.writeMessage(5, getDateFin());
    }
    if (!getPreferencesBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, preferences_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (client_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getClient());
    }
    if (chambre_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getChambre());
    }
    if (dateDebut_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getDateDebut());
    }
    if (dateFin_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getDateFin());
    }
    if (!getPreferencesBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, preferences_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ma.projet.grpc.stubs.Reservation)) {
      return super.equals(obj);
    }
    ma.projet.grpc.stubs.Reservation other = (ma.projet.grpc.stubs.Reservation) obj;

    if (getId()
        != other.getId()) return false;
    if (hasClient() != other.hasClient()) return false;
    if (hasClient()) {
      if (!getClient()
          .equals(other.getClient())) return false;
    }
    if (hasChambre() != other.hasChambre()) return false;
    if (hasChambre()) {
      if (!getChambre()
          .equals(other.getChambre())) return false;
    }
    if (hasDateDebut() != other.hasDateDebut()) return false;
    if (hasDateDebut()) {
      if (!getDateDebut()
          .equals(other.getDateDebut())) return false;
    }
    if (hasDateFin() != other.hasDateFin()) return false;
    if (hasDateFin()) {
      if (!getDateFin()
          .equals(other.getDateFin())) return false;
    }
    if (!getPreferences()
        .equals(other.getPreferences())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    if (hasClient()) {
      hash = (37 * hash) + CLIENT_FIELD_NUMBER;
      hash = (53 * hash) + getClient().hashCode();
    }
    if (hasChambre()) {
      hash = (37 * hash) + CHAMBRE_FIELD_NUMBER;
      hash = (53 * hash) + getChambre().hashCode();
    }
    if (hasDateDebut()) {
      hash = (37 * hash) + DATEDEBUT_FIELD_NUMBER;
      hash = (53 * hash) + getDateDebut().hashCode();
    }
    if (hasDateFin()) {
      hash = (37 * hash) + DATEFIN_FIELD_NUMBER;
      hash = (53 * hash) + getDateFin().hashCode();
    }
    hash = (37 * hash) + PREFERENCES_FIELD_NUMBER;
    hash = (53 * hash) + getPreferences().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ma.projet.grpc.stubs.Reservation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ma.projet.grpc.stubs.Reservation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ma.projet.grpc.stubs.Reservation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ma.projet.grpc.stubs.Reservation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ma.projet.grpc.stubs.Reservation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ma.projet.grpc.stubs.Reservation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ma.projet.grpc.stubs.Reservation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ma.projet.grpc.stubs.Reservation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ma.projet.grpc.stubs.Reservation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ma.projet.grpc.stubs.Reservation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ma.projet.grpc.stubs.Reservation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ma.projet.grpc.stubs.Reservation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ma.projet.grpc.stubs.Reservation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Message pour la réservation
   * </pre>
   *
   * Protobuf type {@code Reservation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Reservation)
      ma.projet.grpc.stubs.ReservationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ma.projet.grpc.stubs.ReservationOuterClass.internal_static_Reservation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ma.projet.grpc.stubs.ReservationOuterClass.internal_static_Reservation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ma.projet.grpc.stubs.Reservation.class, ma.projet.grpc.stubs.Reservation.Builder.class);
    }

    // Construct using ma.projet.grpc.stubs.Reservation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      if (clientBuilder_ == null) {
        client_ = null;
      } else {
        client_ = null;
        clientBuilder_ = null;
      }
      if (chambreBuilder_ == null) {
        chambre_ = null;
      } else {
        chambre_ = null;
        chambreBuilder_ = null;
      }
      if (dateDebutBuilder_ == null) {
        dateDebut_ = null;
      } else {
        dateDebut_ = null;
        dateDebutBuilder_ = null;
      }
      if (dateFinBuilder_ == null) {
        dateFin_ = null;
      } else {
        dateFin_ = null;
        dateFinBuilder_ = null;
      }
      preferences_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ma.projet.grpc.stubs.ReservationOuterClass.internal_static_Reservation_descriptor;
    }

    @java.lang.Override
    public ma.projet.grpc.stubs.Reservation getDefaultInstanceForType() {
      return ma.projet.grpc.stubs.Reservation.getDefaultInstance();
    }

    @java.lang.Override
    public ma.projet.grpc.stubs.Reservation build() {
      ma.projet.grpc.stubs.Reservation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ma.projet.grpc.stubs.Reservation buildPartial() {
      ma.projet.grpc.stubs.Reservation result = new ma.projet.grpc.stubs.Reservation(this);
      result.id_ = id_;
      if (clientBuilder_ == null) {
        result.client_ = client_;
      } else {
        result.client_ = clientBuilder_.build();
      }
      if (chambreBuilder_ == null) {
        result.chambre_ = chambre_;
      } else {
        result.chambre_ = chambreBuilder_.build();
      }
      if (dateDebutBuilder_ == null) {
        result.dateDebut_ = dateDebut_;
      } else {
        result.dateDebut_ = dateDebutBuilder_.build();
      }
      if (dateFinBuilder_ == null) {
        result.dateFin_ = dateFin_;
      } else {
        result.dateFin_ = dateFinBuilder_.build();
      }
      result.preferences_ = preferences_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ma.projet.grpc.stubs.Reservation) {
        return mergeFrom((ma.projet.grpc.stubs.Reservation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ma.projet.grpc.stubs.Reservation other) {
      if (other == ma.projet.grpc.stubs.Reservation.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.hasClient()) {
        mergeClient(other.getClient());
      }
      if (other.hasChambre()) {
        mergeChambre(other.getChambre());
      }
      if (other.hasDateDebut()) {
        mergeDateDebut(other.getDateDebut());
      }
      if (other.hasDateFin()) {
        mergeDateFin(other.getDateFin());
      }
      if (!other.getPreferences().isEmpty()) {
        preferences_ = other.preferences_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ma.projet.grpc.stubs.Reservation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ma.projet.grpc.stubs.Reservation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <pre>
     * ID de la réservation
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }
    /**
     * <pre>
     * ID de la réservation
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ID de la réservation
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private ma.projet.grpc.stubs.Client client_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ma.projet.grpc.stubs.Client, ma.projet.grpc.stubs.Client.Builder, ma.projet.grpc.stubs.ClientOrBuilder> clientBuilder_;
    /**
     * <pre>
     * Le client qui effectue la réservation
     * </pre>
     *
     * <code>.Client client = 2;</code>
     * @return Whether the client field is set.
     */
    public boolean hasClient() {
      return clientBuilder_ != null || client_ != null;
    }
    /**
     * <pre>
     * Le client qui effectue la réservation
     * </pre>
     *
     * <code>.Client client = 2;</code>
     * @return The client.
     */
    public ma.projet.grpc.stubs.Client getClient() {
      if (clientBuilder_ == null) {
        return client_ == null ? ma.projet.grpc.stubs.Client.getDefaultInstance() : client_;
      } else {
        return clientBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Le client qui effectue la réservation
     * </pre>
     *
     * <code>.Client client = 2;</code>
     */
    public Builder setClient(ma.projet.grpc.stubs.Client value) {
      if (clientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        client_ = value;
        onChanged();
      } else {
        clientBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Le client qui effectue la réservation
     * </pre>
     *
     * <code>.Client client = 2;</code>
     */
    public Builder setClient(
        ma.projet.grpc.stubs.Client.Builder builderForValue) {
      if (clientBuilder_ == null) {
        client_ = builderForValue.build();
        onChanged();
      } else {
        clientBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Le client qui effectue la réservation
     * </pre>
     *
     * <code>.Client client = 2;</code>
     */
    public Builder mergeClient(ma.projet.grpc.stubs.Client value) {
      if (clientBuilder_ == null) {
        if (client_ != null) {
          client_ =
            ma.projet.grpc.stubs.Client.newBuilder(client_).mergeFrom(value).buildPartial();
        } else {
          client_ = value;
        }
        onChanged();
      } else {
        clientBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Le client qui effectue la réservation
     * </pre>
     *
     * <code>.Client client = 2;</code>
     */
    public Builder clearClient() {
      if (clientBuilder_ == null) {
        client_ = null;
        onChanged();
      } else {
        client_ = null;
        clientBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Le client qui effectue la réservation
     * </pre>
     *
     * <code>.Client client = 2;</code>
     */
    public ma.projet.grpc.stubs.Client.Builder getClientBuilder() {
      
      onChanged();
      return getClientFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Le client qui effectue la réservation
     * </pre>
     *
     * <code>.Client client = 2;</code>
     */
    public ma.projet.grpc.stubs.ClientOrBuilder getClientOrBuilder() {
      if (clientBuilder_ != null) {
        return clientBuilder_.getMessageOrBuilder();
      } else {
        return client_ == null ?
            ma.projet.grpc.stubs.Client.getDefaultInstance() : client_;
      }
    }
    /**
     * <pre>
     * Le client qui effectue la réservation
     * </pre>
     *
     * <code>.Client client = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ma.projet.grpc.stubs.Client, ma.projet.grpc.stubs.Client.Builder, ma.projet.grpc.stubs.ClientOrBuilder> 
        getClientFieldBuilder() {
      if (clientBuilder_ == null) {
        clientBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ma.projet.grpc.stubs.Client, ma.projet.grpc.stubs.Client.Builder, ma.projet.grpc.stubs.ClientOrBuilder>(
                getClient(),
                getParentForChildren(),
                isClean());
        client_ = null;
      }
      return clientBuilder_;
    }

    private ma.projet.grpc.stubs.Chambre chambre_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ma.projet.grpc.stubs.Chambre, ma.projet.grpc.stubs.Chambre.Builder, ma.projet.grpc.stubs.ChambreOrBuilder> chambreBuilder_;
    /**
     * <pre>
     * La chambre réservée
     * </pre>
     *
     * <code>.Chambre chambre = 3;</code>
     * @return Whether the chambre field is set.
     */
    public boolean hasChambre() {
      return chambreBuilder_ != null || chambre_ != null;
    }
    /**
     * <pre>
     * La chambre réservée
     * </pre>
     *
     * <code>.Chambre chambre = 3;</code>
     * @return The chambre.
     */
    public ma.projet.grpc.stubs.Chambre getChambre() {
      if (chambreBuilder_ == null) {
        return chambre_ == null ? ma.projet.grpc.stubs.Chambre.getDefaultInstance() : chambre_;
      } else {
        return chambreBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * La chambre réservée
     * </pre>
     *
     * <code>.Chambre chambre = 3;</code>
     */
    public Builder setChambre(ma.projet.grpc.stubs.Chambre value) {
      if (chambreBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        chambre_ = value;
        onChanged();
      } else {
        chambreBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * La chambre réservée
     * </pre>
     *
     * <code>.Chambre chambre = 3;</code>
     */
    public Builder setChambre(
        ma.projet.grpc.stubs.Chambre.Builder builderForValue) {
      if (chambreBuilder_ == null) {
        chambre_ = builderForValue.build();
        onChanged();
      } else {
        chambreBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * La chambre réservée
     * </pre>
     *
     * <code>.Chambre chambre = 3;</code>
     */
    public Builder mergeChambre(ma.projet.grpc.stubs.Chambre value) {
      if (chambreBuilder_ == null) {
        if (chambre_ != null) {
          chambre_ =
            ma.projet.grpc.stubs.Chambre.newBuilder(chambre_).mergeFrom(value).buildPartial();
        } else {
          chambre_ = value;
        }
        onChanged();
      } else {
        chambreBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * La chambre réservée
     * </pre>
     *
     * <code>.Chambre chambre = 3;</code>
     */
    public Builder clearChambre() {
      if (chambreBuilder_ == null) {
        chambre_ = null;
        onChanged();
      } else {
        chambre_ = null;
        chambreBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * La chambre réservée
     * </pre>
     *
     * <code>.Chambre chambre = 3;</code>
     */
    public ma.projet.grpc.stubs.Chambre.Builder getChambreBuilder() {
      
      onChanged();
      return getChambreFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * La chambre réservée
     * </pre>
     *
     * <code>.Chambre chambre = 3;</code>
     */
    public ma.projet.grpc.stubs.ChambreOrBuilder getChambreOrBuilder() {
      if (chambreBuilder_ != null) {
        return chambreBuilder_.getMessageOrBuilder();
      } else {
        return chambre_ == null ?
            ma.projet.grpc.stubs.Chambre.getDefaultInstance() : chambre_;
      }
    }
    /**
     * <pre>
     * La chambre réservée
     * </pre>
     *
     * <code>.Chambre chambre = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ma.projet.grpc.stubs.Chambre, ma.projet.grpc.stubs.Chambre.Builder, ma.projet.grpc.stubs.ChambreOrBuilder> 
        getChambreFieldBuilder() {
      if (chambreBuilder_ == null) {
        chambreBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ma.projet.grpc.stubs.Chambre, ma.projet.grpc.stubs.Chambre.Builder, ma.projet.grpc.stubs.ChambreOrBuilder>(
                getChambre(),
                getParentForChildren(),
                isClean());
        chambre_ = null;
      }
      return chambreBuilder_;
    }

    private com.google.protobuf.Timestamp dateDebut_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateDebutBuilder_;
    /**
     * <pre>
     * Date de début de la réservation
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateDebut = 4;</code>
     * @return Whether the dateDebut field is set.
     */
    public boolean hasDateDebut() {
      return dateDebutBuilder_ != null || dateDebut_ != null;
    }
    /**
     * <pre>
     * Date de début de la réservation
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateDebut = 4;</code>
     * @return The dateDebut.
     */
    public com.google.protobuf.Timestamp getDateDebut() {
      if (dateDebutBuilder_ == null) {
        return dateDebut_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateDebut_;
      } else {
        return dateDebutBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Date de début de la réservation
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateDebut = 4;</code>
     */
    public Builder setDateDebut(com.google.protobuf.Timestamp value) {
      if (dateDebutBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dateDebut_ = value;
        onChanged();
      } else {
        dateDebutBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Date de début de la réservation
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateDebut = 4;</code>
     */
    public Builder setDateDebut(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dateDebutBuilder_ == null) {
        dateDebut_ = builderForValue.build();
        onChanged();
      } else {
        dateDebutBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Date de début de la réservation
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateDebut = 4;</code>
     */
    public Builder mergeDateDebut(com.google.protobuf.Timestamp value) {
      if (dateDebutBuilder_ == null) {
        if (dateDebut_ != null) {
          dateDebut_ =
            com.google.protobuf.Timestamp.newBuilder(dateDebut_).mergeFrom(value).buildPartial();
        } else {
          dateDebut_ = value;
        }
        onChanged();
      } else {
        dateDebutBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Date de début de la réservation
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateDebut = 4;</code>
     */
    public Builder clearDateDebut() {
      if (dateDebutBuilder_ == null) {
        dateDebut_ = null;
        onChanged();
      } else {
        dateDebut_ = null;
        dateDebutBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Date de début de la réservation
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateDebut = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDateDebutBuilder() {
      
      onChanged();
      return getDateDebutFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Date de début de la réservation
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateDebut = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDateDebutOrBuilder() {
      if (dateDebutBuilder_ != null) {
        return dateDebutBuilder_.getMessageOrBuilder();
      } else {
        return dateDebut_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : dateDebut_;
      }
    }
    /**
     * <pre>
     * Date de début de la réservation
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateDebut = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDateDebutFieldBuilder() {
      if (dateDebutBuilder_ == null) {
        dateDebutBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDateDebut(),
                getParentForChildren(),
                isClean());
        dateDebut_ = null;
      }
      return dateDebutBuilder_;
    }

    private com.google.protobuf.Timestamp dateFin_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateFinBuilder_;
    /**
     * <pre>
     * Date de fin de la réservation
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateFin = 5;</code>
     * @return Whether the dateFin field is set.
     */
    public boolean hasDateFin() {
      return dateFinBuilder_ != null || dateFin_ != null;
    }
    /**
     * <pre>
     * Date de fin de la réservation
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateFin = 5;</code>
     * @return The dateFin.
     */
    public com.google.protobuf.Timestamp getDateFin() {
      if (dateFinBuilder_ == null) {
        return dateFin_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : dateFin_;
      } else {
        return dateFinBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Date de fin de la réservation
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateFin = 5;</code>
     */
    public Builder setDateFin(com.google.protobuf.Timestamp value) {
      if (dateFinBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dateFin_ = value;
        onChanged();
      } else {
        dateFinBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Date de fin de la réservation
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateFin = 5;</code>
     */
    public Builder setDateFin(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dateFinBuilder_ == null) {
        dateFin_ = builderForValue.build();
        onChanged();
      } else {
        dateFinBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Date de fin de la réservation
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateFin = 5;</code>
     */
    public Builder mergeDateFin(com.google.protobuf.Timestamp value) {
      if (dateFinBuilder_ == null) {
        if (dateFin_ != null) {
          dateFin_ =
            com.google.protobuf.Timestamp.newBuilder(dateFin_).mergeFrom(value).buildPartial();
        } else {
          dateFin_ = value;
        }
        onChanged();
      } else {
        dateFinBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Date de fin de la réservation
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateFin = 5;</code>
     */
    public Builder clearDateFin() {
      if (dateFinBuilder_ == null) {
        dateFin_ = null;
        onChanged();
      } else {
        dateFin_ = null;
        dateFinBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Date de fin de la réservation
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateFin = 5;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDateFinBuilder() {
      
      onChanged();
      return getDateFinFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Date de fin de la réservation
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateFin = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDateFinOrBuilder() {
      if (dateFinBuilder_ != null) {
        return dateFinBuilder_.getMessageOrBuilder();
      } else {
        return dateFin_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : dateFin_;
      }
    }
    /**
     * <pre>
     * Date de fin de la réservation
     * </pre>
     *
     * <code>.google.protobuf.Timestamp dateFin = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDateFinFieldBuilder() {
      if (dateFinBuilder_ == null) {
        dateFinBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDateFin(),
                getParentForChildren(),
                isClean());
        dateFin_ = null;
      }
      return dateFinBuilder_;
    }

    private java.lang.Object preferences_ = "";
    /**
     * <pre>
     * Préférences du client
     * </pre>
     *
     * <code>string preferences = 6;</code>
     * @return The preferences.
     */
    public java.lang.String getPreferences() {
      java.lang.Object ref = preferences_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        preferences_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Préférences du client
     * </pre>
     *
     * <code>string preferences = 6;</code>
     * @return The bytes for preferences.
     */
    public com.google.protobuf.ByteString
        getPreferencesBytes() {
      java.lang.Object ref = preferences_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        preferences_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Préférences du client
     * </pre>
     *
     * <code>string preferences = 6;</code>
     * @param value The preferences to set.
     * @return This builder for chaining.
     */
    public Builder setPreferences(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      preferences_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Préférences du client
     * </pre>
     *
     * <code>string preferences = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPreferences() {
      
      preferences_ = getDefaultInstance().getPreferences();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Préférences du client
     * </pre>
     *
     * <code>string preferences = 6;</code>
     * @param value The bytes for preferences to set.
     * @return This builder for chaining.
     */
    public Builder setPreferencesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      preferences_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Reservation)
  }

  // @@protoc_insertion_point(class_scope:Reservation)
  private static final ma.projet.grpc.stubs.Reservation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ma.projet.grpc.stubs.Reservation();
  }

  public static ma.projet.grpc.stubs.Reservation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Reservation>
      PARSER = new com.google.protobuf.AbstractParser<Reservation>() {
    @java.lang.Override
    public Reservation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Reservation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Reservation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Reservation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ma.projet.grpc.stubs.Reservation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

